function LanguageAbbrevations() {
  return {
    en: "English",
    es: "Spanish",
    fr: "French",
    de: "German",
    it: "Italian",
    pt: "Portuguese",
    nl: "Dutch",
    ru: "Russian",
    zh: "Chinese",
    ja: "Japanese",
    ko: "Korean",
    ar: "Arabic",
    hi: "Hindi",
    bn: "Bengali",
    ur: "Urdu",
    te: "Telugu",
    ta: "Tamil",
    ml: "Malayalam",
    fi: "Finnish",
    sv: "Swedish",
    no: "Norwegian",
    da: "Danish",
    is: "Icelandic",
    pl: "Polish",
    cs: "Czech",
    hu: "Hungarian",
    tr: "Turkish",
    el: "Greek",
    th: "Thai",
    vi: "Vietnamese",
    id: "Indonesian",
    ms: "Malay",
    fil: "Filipino",
    he: "Hebrew",
    fa: "Persian",
    si: "Sinhala",
    sw: "Swahili",
    am: "Amharic",
    km: "Khmer",
    my: "Burmese",
    ne: "Nepali",
    pa: "Punjabi",
    gu: "Gujarati",
    kn: "Kannada",
    mr: "Marathi",
    sd: "Sindhi",
    bo: "Tibetan",
    ug: "Uighur",
    ky: "Kyrgyz",
    tt: "Tatar",
    // Add more mappings as needed
  };
}

export default LanguageAbbrevations;
